---
apiVersion: v1
kind: Namespace
metadata:
  name: telemetry
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: telemetry
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 75.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-stack
        namespace: telemetry
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
    timeout: 10m
  valuesFrom:
    - kind: ConfigMap
      name: cluster-config
      valuesKey: grafana_root_url
      targetPath: grafana.grafana.ini.server.root_url
    - kind: ConfigMap
      name: cluster-config
      valuesKey: hostname
      targetPath: grafana.grafana.ini.server.domain
    - kind: ConfigMap
      name: cluster-config
      valuesKey: hostname
      targetPath: grafana.ingress.tls[0].hosts[0]
  values:
    grafana:
      grafana.ini:
        server:
          enforce_domain: false