---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 75.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-stack
        namespace: flux=system
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: cluster-config
      valuesKey: grafana_root_url
      targetPath: grafana.grafana.ini.server.root_url
    - kind: ConfigMap
      name: cluster-config
      valuesKey: hostname
      targetPath: grafana.grafana.ini.server.domain
    - kind: ConfigMap
      name: cluster-config
      valuesKey: hostname
      targetPath: grafana.ingress.tls[0].hosts[0]
  values:
    grafana:
      grafana.ini:
        server:
          enforce_domain: false
      # ingress:
      #   enabled: true
      #   ingressClassName: nginx
      #   annotations:
      #     cert-manager.io/cluster-issuer: letsencrypt
      #     nginx.ingress.kubernetes.io/rewrite-target: /$2
      #     nginx.ingress.kubernetes.io/use-regex: "true"
      #   paths:
      #     - path: /grafana(/|$)(.*)
      #       pathType: Prefix
      #   tls:
      #     - secretName: grafana-tls
      # service:
      #   type: ClusterIP
      #   port: 80