---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-stack
  namespace: telemetry
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts