{{- $cfg := lookup "v1" "ConfigMap" "flux-system" "cluster-config" }}
{{- $host := get $cfg.data "hostname" }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-dashboard
  namespace: telemetry
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - {{ $host }}
    secretName: grafana-dash-tls
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: prometheus-stack-grafana
                port:
                  number: 3000
