apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: calico
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/projectcalico/calico
  ref:
    tag: v3.25.0