apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: projectcalico
  namespace: flux-system
spec:
  interval: 60m
  url: https://projectcalico.docs.tigera.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: tigera-operator
      version: 3.30.0
      sourceRef:
        kind: HelmRepository
        name: projectcalico
        namespace: flux-system
  values:
    installation:
      kubernetesProvider: "k8s"