apiVersion: v1
kind: Namespace
metadata:
  name: tigera-operaton
  labels:
    name: tigera-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: calico
  namespace: flux-system
spec:
  interval: 60m
  url: https://projectcalico.docs.tigera.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calico
  namespace: tigera-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: tigera-operator
      version: 3.30.0
      sourceRef:
        kind: HelmRepository
        name: calico
        namespace: flux-system
  values:
    installation:
      kubernetesProvider: ""