apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-ingress
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/grafana-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config
  dependsOn:
    - name: prometheus-stack
      namespace: flux-system
