apiVersion: v1
kind: Namespace
metadata:
  name: id
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
  namespace: id
spec:
  instances: 3
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${auth_db_name}
  namespace: id
spec:
  description: "Simple pg cluster for keycloack"
  bootstrap:
    initdb:
      database: ${auth_db_name}
      owner: ${auth_db_user}
      secret:
        name: keycloak-admin
  instances: 3
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: id
type: Opaque
stringData:
  username: ${auth_db_user}
  password: ${auth_db_password}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloakx
  namespace: id
spec:
  interval: 15m
  chart:
    spec:
      chart: keycloakx
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: keycloakx
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
    timeout: 15m
  values:
    # cache:
    #   config: local
    http:
      relativePath: /keycloak
      httpEnabled: true
      proxyHeaders: forwarded
    metrics:
      enabled: true
    health:
      enabled: true
    database:
      vendor: postgres
      hostname: ${auth_db_name}-rw
      port: 5432
      username: ${auth_db_user}
      database: ${auth_db_name}
      # password: ${auth_db_password}
      existingSecret: keycloak-app
      existingSecretKey: password
      # existingSecretHostKey: host
      # existingSecretPortKey: port
      # existingSecretDatabaseKey: dbname
      # existingSecretUsernameKey: username
      # existingSecretPasswordKey: password
    auth:
      existingSecret: keycloak-admin
      existingSecretAdminUserKey: username
      existingSecretAdminPasswordKey: password
    command:  # Explicitly set command to ensure correct execution
      - "/opt/keycloak/bin/kc.sh"
      - "start"
    args:  # Move arguments here for clarity
      - "--verbose"
      - "--http-port=8080"
      - "--hostname-strict=false"
      - "--log-level=WARN"
      - "--spi-events-listener-jboss-logging-success-level=info"
      - "--spi-events-listener-jboss-logging-error-level=warn"
    # extraEnv: |
    #   - name: KC_BOOTSTRAP_ADMIN_USERNAME
    #     valueFrom:
    #       secretKeyRef:
    #         name: keycloak-admin
    #         key: username
    #   - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    #     valueFrom:
    #       secretKeyRef:
    #         name: keycloak-admin
    #         key: password
    #   - name: JAVA_OPTS_APPEND
    #     value: >-
    #       -XX:MaxRAMPercentage=50.0
    #       -Djgroups.dns.query=keycloakx-headless
    #   - name: KC_DB_URL_HOST
    #     valueFrom:
    #       secretKeyRef:
    #         name: keycloak-app
    #         key: host
    #   - name: KC_DB_URL_PORT
    #     valueFrom:
    #       secretKeyRef:
    #         name: keycloak-app
    #         key: port
    #   - name: KC_DB_URL_DATABASE
    #     valueFrom:
    #       secretKeyRef:
    #         name: keycloak-app
    #         key: dbname
    #   - name: KC_DB_USERNAME
    #     valueFrom:
    #       secretKeyRef:
    #         name: keycloak-app
    #         key: username
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1024Mi"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: id
spec:
  interval: 15m
  chart:
    spec:
      chart: oauth2-proxy
      version: 8.1.1
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
    timeout: 15m
  values: