---
apiVersion: v1
kind: Namespace
metadata:
  name: id
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloakx
  namespace: id
spec:
  interval: 15m
  chart:
    spec:
      chart: keycloakx
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: keycloakx
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
    timeout: 10m
  values:
    crds:
      enabled: true
    webhook:
      timeoutSeconds: 30