---
apiVersion: v1
kind: Namespace
metadata:
  name: id
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloakx
  namespace: id
spec:
  interval: 15m
  chart:
    spec:
      chart: keycloakx
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: keycloakx
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
    timeout: 10m
  values:
    crds:
      enabled: true
    webhook:
      timeoutSeconds: 30
    postgresql:
      enabled: false
      existingSecret: keycloak-app
    # database:
    #   vendor: postgres
    #   hostname: mypostgres
    #   port: 5432
    #   username: '{{ .Values.dbUser }}'
    #   password: '{{ .Values.dbPassword }}'
    #   database: mydb
    extraEnv:
      - name: DB_VENDOR
        value: postgres
      - name: DB_ADDR
        valueFrom:
          secretKeyRef:
            name: keycloak-db
            key: host
      - name: DB_PORT
        valueFrom:
          secretKeyRef:
            name: keycloak-db
            key: port
      - name: DB_DATABASE
        valueFrom:
          secretKeyRef:
            name: keycloak-db
            key: dbname
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: keycloak-db
            key: username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-db
            key: password