---
apiVersion: v1
kind: Namespace
metadata:
  name: id
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloakx
  namespace: id
spec:
  interval: 15m
  chart:
    spec:
      chart: keycloakx
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: keycloakx
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
    timeout: 10m
  values:
    crds:
      enabled: true
    webhook:
      timeoutSeconds: 30
    command:
      - "/opt/keycloak/bin/kc.sh"
      - "--verbose"
      - "start"
      - "--http-port=8080"
      - "--hostname-strict=false"
      - "--spi-events-listener-jboss-logging-success-level=info"
      - "--spi-events-listener-jboss-logging-error-level=warn"
    extraEnv: |
      - name: DB_VENDOR
        value: postgres
      - name: KC_DB_URL_HOST
        valueFrom:
          secretKeyRef:
            name: keycloak-app
            key: host
      - name: KC_DB_URL_PORT
        valueFrom:
          secretKeyRef:
            name: keycloak-app
            key: port
      - name: KC_DB_URL_DATABASE
        valueFrom:
          secretKeyRef:
            name: keycloak-app
            key: dbname
      - name: KC_DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: keycloak-app
            key: username
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-app
            key: password