apiVersion: v1
kind: Namespace
metadata:
  name: id
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
  namespace: id
spec:
  instances: 3
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: id
type: Opaque
stringData:
  username: admin
  password: admin1234
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloakx
  namespace: id
spec:
  interval: 15m
  chart:
    spec:
      chart: keycloakx
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: keycloakx
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
    timeout: 15m
  values:
    cache:
      config: local
    http:
      relativePath: /keycloak
      httpEnabled: true
      proxyHeaders: forwarded
    metrics:
      enabled: true
    health:
      enabled: true
    database:
      vendor: postgres
      existingSecret: keycloak-app
      existingSecretHostKey: host
      existingSecretPortKey: port
      existingSecretDatabaseKey: dbname
      existingSecretUsernameKey: username
      existingSecretPasswordKey: password
    auth:
      existingSecret: keycloak-admin
      existingSecretAdminUserKey: username
      existingSecretAdminPasswordKey: password
    extraArgs:
      - "start"
      - "--verbose"
      - "--http-port=8080"
      - "--hostname-strict=false"
      - "--log-level=DEBUG"  # Enable debug logging
      - "--spi-events-listener-jboss-logging-success-level=info"
      - "--spi-events-listener-jboss-logging-error-level=warn"