---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.26.0
      sourceRef:
        kind: HelmRepository
        name: cnpg-system
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
    timeout: 10m
  values:
    config:
      clusterWide: false