---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
    timeout: 10m
  values:
    crds:
      enabled: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
    webhook:
      timeoutSeconds: 30
    startupapicheck:
      timeoutSeconds: 30