apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 60m
  targetNamespace: monitoring
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.7.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
  valuesFrom:
    - kind: ConfigMap
      name: cluster-config
      optional: false
      valuesKey: grafana_root_url
      targetPath: grafana.server.rootUrl