apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  interval: 60m
  targetNamespace: ingress-nginx
  releaseName: nginx-ingress
  chart:
    spec:
      chart: ingress-nginx
      version: "4.8.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
  values:
    controller:
      replicaCount: 1
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443