apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 72.6.3
      sourceRef:
        kind: HelmRepository
        name: kube-prom-stack
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: cluster-config
      valuesKey: grafana_root_url
      targetPath: grafana.grafana.ini.server.root_url
  values:
    grafana:
      grafana.ini:
        server:
          serve_from_sub_path: true
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
        mountPropagation: HostToContainer