apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /grafana
        backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /prometheus
        backend:
          service:
            name: kube-prometheus-stack-prometheus
            port:
              number: 9090
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-prom-stack
  namespace: monitoring
spec:
  interval: 60m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 72.6.3
      sourceRef:
        kind: HelmRepository
        name: kube-prom-stack
        namespace: monitoring
  values:
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
        mountPropagation: HostToContainer
    grafana:
      grafana.ini:
        server:
          root_url: https://${hostname}/grafana/
          serve_from_sub_path: true