apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - helmrelease.yaml
  - helmrepo.yaml
  - ingress.yaml

postBuild:
  substituteFrom:
  - kind: ConfigMap
    name: cluster-config
    namespace: default




