apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepo.yaml
  - helmrelease.yaml
  - ingress.yaml

vars:
  - name: HOSTNAME
    objref:
      kind: ConfigMap
      name: cluster-config
      apiVersion: v1
      namespace: flux-system
    fieldref:
      fieldpath: data.hostname