apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - helmrelease.yaml
  - helmrepo.yaml
  - ingress.yaml
  - cluster-config.yaml

vars:
  - name: HOSTNAME
    objref:
      kind: ConfigMap
      name: cluster-config
      apiVersion: v1
    fieldref:
      fieldpath: data.hostname
