# kind_ovh_flux/clusters/kind_ovh/infra/monitoring/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - helmrelease.yaml
  - helmrepo.yaml
  - ingress.yaml


