apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress
  - monitoring

vars:
- name: HOSTNAME
  objref:
    kind: ConfigMap
    name: cluster-config
    apiVersion: v1
  fieldref:
    fieldpath: data.hostname

patches:
- path: patches/grafana-ingress.yaml
  target:
    kind: Ingress
    name: grafana-ingress
- path: patches/prometheus-ingress.yaml
  target:
    kind: Ingress
    name: prometheus-ingress
