---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
  namespace: id
spec:
  instances: 3
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  # bootstrap:
  #   initdb:
  #     database: ${auth_db_name}
      # owner: ${auth_db_user}
      # dataChecksums: true
      # postInitSQL:
      #   - CREATE DATABASE angu
      # secret:
      #   name: app-secret
---