---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: cnpg-system
type: Opaque
stringData:
  password: "app_test"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-db
  namespace: cnpg-system
spec:
  instances: 3
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: test
      owner: test
      dataChecksums: true
      localeCollate: 'C.UTF-8'
      localeCType: 'C.UTF-8'
      postInitSQL:
        - CREATE DATABASE angu
      secret:
        name: app-secret
---