---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: cnpg-system
type: Opaque
stringData:
  password: "${auth_db_password}"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
  namespace: cnpg-system
spec:
  instances: 3
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  # bootstrap:
  #   initdb:
  #     database: ${auth_db_name}
      # owner: ${auth_db_user}
      # dataChecksums: true
      # postInitSQL:
      #   - CREATE DATABASE angu
      # secret:
      #   name: app-secret
---