apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "61.1.0"
  install:
    createNamespace: true
  values:
    grafana:
      enabled: true
      namespace: monitoring
      adminPassword: "password"
    prometheus:
      enabled: true
      namespace: monitoring
    alertmanager:
      enabled: true
      namespace: monitoring
